### ISSUE TITLE
Support multiple Zabbix instances

### ISSUE THREAD

**Issue by davux** [wriley/ZabbixTray#7]
It would be awesome if ZabbixTray were able to monitor several Zabbix instances instead of just one: as an administrator you are sometimes in charge of multiple networks or systems.

Also:
- Display/alerting preferences should be different depending on the instance
- The user should be able to nickname each instance, and then the name can be used e.g. in the notifications.

What do you think?

**Comment by wriley** [comment]
I haven't used this in years and don't plan on adding any new features. These ideas sound useful so maybe someone that has forked will implement them.
